# .github/workflows/java-ci.yml

name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set environment variables
        run: |
          echo "REDIS_HOST=${{ vars.REDIS_HOST }}" >> $GITHUB_ENV
          echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> $GITHUB_ENV
          echo "REDIS_TIMEOUT=${{ vars.REDIS_TIMEOUT }}" >> $GITHUB_ENV
          echo "MAIL_HOST=${{ vars.MAIL_HOST }}" >> $GITHUB_ENV
          echo "MAIL_PORT=${{ vars.MAIL_PORT }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ vars.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ vars.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "MAIL_SMTP_AUTH=${{ vars.MAIL_SMTP_AUTH }}" >> $GITHUB_ENV
          echo "MAIL_STARTTLS_ENABLE=${{ vars.MAIL_STARTTLS_ENABLE }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ vars.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "JWT_EXPIRATION=${{ vars.JWT_EXPIRATION }}" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_EXPIRATION=${{ vars.JWT_REFRESH_TOKEN_EXPIRATION }}" >> $GITHUB_ENV
          echo "DATASOURCE_URL=${{ vars.DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "DATASOURCE_USERNAME=${{ vars.DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "DATASOURCE_PASSWORD=${{ vars.DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
          echo "DATASOURCE_DRIVER_CLASS_NAME=${{ vars.DATASOURCE_DRIVER_CLASS_NAME }}" >> $GITHUB_ENV
          echo "JPA_HIBERNATE_DDL_AUTO=${{ vars.JPA_HIBERNATE_DDL_AUTO }}" >> $GITHUB_ENV
          echo "JPA_SHOW_SQL=${{ vars.JPA_SHOW_SQL }}" >> $GITHUB_ENV
          echo "JPA_HIBERNATE_FORMAT_SQL=${{ vars.JPA_HIBERNATE_FORMAT_SQL }}" >> $GITHUB_ENV
          echo "JPA_HIBERNATE_DIALECT=${{ vars.JPA_HIBERNATE_DIALECT }}" >> $GITHUB_ENV
          echo "LIQUIBASE_ENABLED=${{ vars.LIQUIBASE_ENABLED }}" >> $GITHUB_ENV
          echo "LIQUIBASE_CHANGE_LOG=${{ vars.LIQUIBASE_CHANGE_LOG }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn -B package --file pom.xml
