# .github/workflows/java-ci.yml

name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set environment variables
        run: |
          echo "REDIS_HOST=${{ vars.REDIS_HOST }}" >> $GITHUB_ENV
          echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> $GITHUB_ENV
          echo "MAIL_HOST=${{ vars.MAIL_HOST }}" >> $GITHUB_ENV
          echo "MAIL_PORT=${{ vars.MAIL_PORT }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ vars.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ vars.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ vars.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "DATASOURCE_URL=${{ vars.DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "DATASOURCE_USERNAME=${{ vars.DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "DATASOURCE_PASSWORD=${{ vars.DATASOURCE_PASSWORD }}" >> $GITHUB_ENV

      - name: Replace placeholders in application.yml
        run: |
          sed -i 's/localhost/${{ vars.REDIS_HOST }}/' src/main/resources/application.yml
          sed -i 's/6379/${{ vars.REDIS_PORT }}/' src/main/resources/application.yml
          sed -i 's/smtp.gmail.com/${{ vars.MAIL_HOST }}/' src/main/resources/application.yml
          sed -i 's/587/${{ vars.MAIL_PORT }}/' src/main/resources/application.yml
          sed -i 's/username:/${{ vars.MAIL_USERNAME }}/' src/main/resources/application.yml
          sed -i 's/password:/${{ vars.MAIL_PASSWORD }}/' src/main/resources/application.yml
          sed -i 's/secret-key:/${{ vars.JWT_SECRET_KEY }}/' src/main/resources/application.yml
          sed -i 's/url:/${{ vars.DATASOURCE_URL }}/' src/main/resources/application.yml
          sed -i 's/username:/${{ vars.DATASOURCE_USERNAME }}/' src/main/resources/application.yml
          sed -i 's/password:/${{ vars.DATASOURCE_PASSWORD }}/' src/main/resources/application.yml

      - name: Build with Maven
        run: mvn -B package --file pom.xml
