# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# .github/workflows/java-ci.yml

name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set environment variables
        run: |
          echo "MAIL_USERNAME=${{ vars.EMAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ vars.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ vars.JWT_SECRET }}" >> $GITHUB_ENV
          echo "DATASOURCE_URL=${{ vars.DB_URL }}" >> $GITHUB_ENV
          echo "DATASOURCE_USERNAME=${{ vars.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DATASOURCE_PASSWORD=${{ vars.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Replace placeholders in application.yml
        run: |
          sed -i 's/username:/${{ vars.MAIL_USERNAME }}/' src/main/resources/application.yml
          sed -i 's/password:/${{ vars.MAIL_PASSWORD }}/' src/main/resources/application.yml
          sed -i 's/secret-key:/${{ vars.JWT_SECRET_KEY }}/' src/main/resources/application.yml
          sed -i 's/url:/${{ vars.DATASOURCE_URL }}/' src/main/resources/application.yml
          sed -i 's/username:/${{ vars.DATASOURCE_USERNAME }}/' src/main/resources/application.yml
          sed -i 's/password:/${{ vars.DATASOURCE_PASSWORD }}/' src/main/resources/application.yml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

