name: SonarCloud Analysis

on:
  push:
    branches:
      - develop

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.organization=TAndrian \
            -Dsonar.projectKey=TAndrian_we-go-jim \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR__CLOUD_TOKEN
